name: twitter_bot

on:  
  workflow_dispatch:
  schedule:
    - cron:  '30 9 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Prepare the environment
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
   
    # Step 2: Install requirements, so Python script can run
    - name: Install requirements
      run: python -m pip install pandas tweepy
    # Step 3    
    - name: Tweet      
      run: python job-search-twitter-bot.py  
      env:
        CONSUMER_KEY: ${{secrets.CONSUMER_KEY  }}
        CONSUMER_SECRET: ${{secrets.CONSUMER_SECRET  }}
        ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN  }}
        ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET  }}
        BEARER_TOKEN: ${{secrets.BEARER_TOKEN  }}
  
    # Step 4
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
